<?xml version="1.0" encoding="UTF-8"?>
 <ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Transport" nsURI="http://atlanmod/transport" nsPrefix="transport">
  <eClassifiers xsi:type="ecore:EClass" name="IDElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Vehicle" eSuperTypes="#//IDElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="follows" eType="#//Route"
        eOpposite="#//Route/isFollowedBy"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bus" eSuperTypes="#//Vehicle"/>
  <eClassifiers xsi:type="ecore:EClass" name="Tram" eSuperTypes="#//Vehicle"/>
  <eClassifiers xsi:type="ecore:EClass" name="Route" eSuperTypes="#//IDElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="isFollowedBy" eType="#//Vehicle"
        eOpposite="#//Vehicle/follows"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contains" upperBound="-1"
        eType="#//Stop" eOpposite="#//Stop/isContained"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Stop" eSuperTypes="#//IDElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="isContained" eType="#//Route"
        eOpposite="#//Route/contains"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lat" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lon" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="handicap" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Network">
    <eStructuralFeatures xsi:type="ecore:EReference" name="vehicules" upperBound="-1"
        eType="#//Vehicle" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="routes" upperBound="-1"
        eType="#//Route" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stops" upperBound="-1"
        eType="#//Stop" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
